// 45 effects for ATM.playSfx(track, channel). Each is a normal one-track ATMlib command stream;
// ATM_SFX_TRACK() appends ATM_STOP_CHAN. sizeof() = the byte size shown on screen.
// Timing is in song ticks, so the effects get faster or slower with the song tempo (36..44 here).
// One track only: no GOTO/REPEAT. One slide slot per channel (SL_VOL or SL_FRQ, not both).
#ifndef ATMSFX_H
#define ATMSFX_H

ATM_SFX_TRACK(aJump, ATM_VOL(50), ATM_SL_VOL((uint8_t)-3), ATM_GLIS(0), ATM_NOTE_C4, ATM_DELAY(14));   // Jump
ATM_SFX_TRACK(aCoin, ATM_VOL(45), ATM_SL_VOL((uint8_t)-3), ATM_NOTE_B5, ATM_DELAY(2), ATM_NOTE_E6, ATM_DELAY(12));   // Coin
ATM_SFX_TRACK(aLaser, ATM_VOL(55), ATM_SL_FRQ((uint8_t)-100), ATM_NOTE_C7, ATM_DELAY(14));   // Laser
ATM_SFX_TRACK(aHit, ATM_VOL(55), ATM_SL_VOL((uint8_t)-7), ATM_NOTE_C5, ATM_DELAY(8));   // Hit
ATM_SFX_TRACK(aExplode, ATM_VOL(63), ATM_SL_VOL((uint8_t)-2), ATM_NOTE_C3, ATM_DELAY(32));   // Explode
ATM_SFX_TRACK(aPowerUp, ATM_VOL(40), ATM_SL_VOL((uint8_t)-2), ATM_NOTE_C5, ATM_DELAY(2), ATM_NOTE_E5, ATM_DELAY(2), ATM_NOTE_G5, ATM_DELAY(2), ATM_NOTE_C6, ATM_DELAY(12));   // PowerUp
ATM_SFX_TRACK(aSelect, ATM_VOL(40), ATM_SL_VOL((uint8_t)-5), ATM_NOTE_A5, ATM_DELAY(6));   // Select
ATM_SFX_TRACK(aFail, ATM_VOL(45), ATM_SL_VOL((uint8_t)-1), ATM_GLIS(0x81), ATM_NOTE_A3, ATM_DELAY(24));   // Fail
ATM_SFX_TRACK(aBlip, ATM_VOL(35), ATM_SL_VOL((uint8_t)-6), ATM_NOTE_E6, ATM_DELAY(5));   // Blip
ATM_SFX_TRACK(aWhoosh, ATM_VOL(2), ATM_SL_VOL(5), ATM_NOTE_C4, ATM_DELAY(7), ATM_SL_VOL((uint8_t)-6), ATM_DELAY(8));   // Whoosh
ATM_SFX_TRACK(aSiren, ATM_VOL(35), ATM_NOTE_A4, ATM_DELAY(4), ATM_NOTE_E5, ATM_DELAY(4), ATM_NOTE_A4, ATM_DELAY(4), ATM_NOTE_E5, ATM_DELAY(4), ATM_NOTE_A4, ATM_DELAY(4), ATM_NOTE_E5, ATM_DELAY(4));   // Siren
ATM_SFX_TRACK(aGem, ATM_VOL(40), ATM_SL_VOL((uint8_t)-1), ATM_ARP(0x43, 0x20), ATM_NOTE_C6, ATM_DELAY(16));   // Gem
ATM_SFX_TRACK(aBounce, ATM_SL_VOL((uint8_t)-3), ATM_VOL(60), ATM_NOTE_G2, ATM_DELAY(5), ATM_VOL(40), ATM_NOTE_G2, ATM_DELAY(4), ATM_VOL(24), ATM_NOTE_G2, ATM_DELAY(3), ATM_VOL(12), ATM_NOTE_G2, ATM_DELAY(3));   // Bounce
ATM_SFX_TRACK(aWarp, ATM_VOL(40), ATM_SL_VOL((uint8_t)-1), ATM_GLIS(0), ATM_NOTE_C3, ATM_DELAY(30));   // Warp
ATM_SFX_TRACK(aPowerDn, ATM_VOL(40), ATM_SL_VOL((uint8_t)-2), ATM_NOTE_C6, ATM_DELAY(3), ATM_NOTE_G5, ATM_DELAY(3), ATM_NOTE_E5, ATM_DELAY(3), ATM_NOTE_C5, ATM_DELAY(10));   // PowerDown
ATM_SFX_TRACK(aAlarm, ATM_VOL(40), ATM_TREM(12, 1), ATM_NOTE_A5, ATM_DELAY(7), ATM_NOTE_F5, ATM_DELAY(7));   // Alarm
ATM_SFX_TRACK(aClick, ATM_VOL(40), ATM_SL_VOL((uint8_t)-20), ATM_NOTE_C6, ATM_DELAY(2));   // Click
ATM_SFX_TRACK(aThud, ATM_VOL(63), ATM_SL_VOL((uint8_t)-6), ATM_GLIS(0x80), ATM_NOTE_G2, ATM_DELAY(9));   // Thud
ATM_SFX_TRACK(aZip, ATM_VOL(40), ATM_SL_VOL((uint8_t)-4), ATM_GLIS(0x80), ATM_NOTE_C7, ATM_DELAY(10));   // Zip
ATM_SFX_TRACK(aMagic, ATM_VOL(36), ATM_SL_VOL((uint8_t)-1), ATM_VIB(4, 1), ATM_NOTE_G6, ATM_DELAY(8), ATM_NOTE_C7, ATM_DELAY(14));   // Magic
ATM_SFX_TRACK(aNPick, ATM_VOL(40), ATM_SL_VOL((uint8_t)-2), ATM_NOTE_E5, ATM_DELAY(1), ATM_NOTE_G5, ATM_DELAY(1), ATM_NOTE_E6, ATM_DELAY(1), ATM_NOTE_G6, ATM_DELAY(9));   // NES Pick
ATM_SFX_TRACK(aNShot, ATM_VOL(50), ATM_SL_FRQ((uint8_t)-110), ATM_NOTE_G6, ATM_DELAY(8));   // NES Shot
ATM_SFX_TRACK(aNStomp, ATM_VOL(55), ATM_SL_VOL((uint8_t)-5), ATM_GLIS(0x80), ATM_NOTE_G3, ATM_DELAY(10));   // NES Stomp
ATM_SFX_TRACK(aN1up, ATM_VOL(40), ATM_SL_VOL((uint8_t)-1), ATM_NOTE_E5, ATM_DELAY(2), ATM_NOTE_G5, ATM_DELAY(2), ATM_NOTE_E6, ATM_DELAY(2), ATM_NOTE_C6, ATM_DELAY(2), ATM_NOTE_D6, ATM_DELAY(2), ATM_NOTE_G6, ATM_DELAY(12));   // NES 1UP
ATM_SFX_TRACK(aNPipe, ATM_VOL(45), ATM_SL_VOL((uint8_t)-1), ATM_GLIS(0x80), ATM_NOTE_C5, ATM_DELAY(20));   // NES Pipe
ATM_SFX_TRACK(aNFire, ATM_VOL(45), ATM_SL_VOL((uint8_t)-3), ATM_NOTE_C4, ATM_DELAY(14));   // NES Fire
ATM_SFX_TRACK(aNBlock, ATM_VOL(50), ATM_SL_VOL((uint8_t)-8), ATM_NOTE_A3, ATM_DELAY(2), ATM_NOTE_E3, ATM_DELAY(6));   // NES Block
ATM_SFX_TRACK(aNDash, ATM_VOL(2), ATM_SL_VOL(8), ATM_NOTE_E4, ATM_DELAY(3), ATM_SL_VOL((uint8_t)-8), ATM_DELAY(5));   // NES Dash
ATM_SFX_TRACK(aNDead, ATM_VOL(45), ATM_SL_VOL((uint8_t)-1), ATM_NOTE_B5, ATM_DELAY(4), ATM_GLIS(0x80), ATM_NOTE_B4, ATM_DELAY(20));   // NES Dead
ATM_SFX_TRACK(aNBeep, ATM_VOL(35), ATM_SL_VOL((uint8_t)-2), ATM_NOTE_B5, ATM_DELAY(3), ATM_NOTE_B5, ATM_DELAY(3));   // NES Beep
ATM_SFX_TRACK(aTPew, ATM_VOL(55), ATM_SL_FRQ((uint8_t)-110), ATM_NOTE_G6, ATM_DELAY(10));   // ATA Pew
ATM_SFX_TRACK(aTCrash, ATM_VOL(63), ATM_SL_VOL((uint8_t)-1), ATM_NOTE_C2, ATM_DELAY(48));   // ATA Crash
ATM_SFX_TRACK(aTBuzz, ATM_VOL(40), ATM_SL_VOL((uint8_t)-1), ATM_TREM(10, 0), ATM_NOTE_A2, ATM_DELAY(14));   // ATA Buzz
ATM_SFX_TRACK(aTBomb, ATM_VOL(60), ATM_SL_VOL((uint8_t)-2), ATM_GLIS(0x81), ATM_NOTE_C3, ATM_DELAY(24));   // ATA Bomb
ATM_SFX_TRACK(aTBlip, ATM_VOL(40), ATM_SL_VOL((uint8_t)-6), ATM_NOTE_A4, ATM_DELAY(5));   // ATA Blip
ATM_SFX_TRACK(aTZap, ATM_VOL(45), ATM_SL_FRQ(60), ATM_NOTE_A4, ATM_DELAY(8));   // ATA Zap
ATM_SFX_TRACK(aTLose, ATM_VOL(45), ATM_SL_VOL((uint8_t)-1), ATM_NOTE_C4, ATM_DELAY(4), ATM_NOTE_A3, ATM_DELAY(4), ATM_NOTE_F3_, ATM_DELAY(4), ATM_NOTE_D3, ATM_DELAY(10));   // ATA Lose
ATM_SFX_TRACK(aTRumb, ATM_VOL(55), ATM_SL_VOL((uint8_t)-2), ATM_VIB(6, 0), ATM_NOTE_C2, ATM_DELAY(28));   // ATA Rumb
ATM_SFX_TRACK(aTTick, ATM_VOL(35), ATM_SL_VOL((uint8_t)-18), ATM_NOTE_C6, ATM_DELAY(2));   // ATA Tick
ATM_SFX_TRACK(aTWin, ATM_VOL(40), ATM_SL_VOL((uint8_t)-1), ATM_NOTE_C4, ATM_DELAY(3), ATM_NOTE_E4, ATM_DELAY(3), ATM_NOTE_G4, ATM_DELAY(3), ATM_NOTE_C5, ATM_DELAY(10));   // ATA Win
ATM_SFX_TRACK(aGRing, ATM_VOL(40), ATM_SL_VOL((uint8_t)-1), ATM_NOTE_A5, ATM_DELAY(3), ATM_NOTE_E6, ATM_DELAY(14));   // SEG Ring
ATM_SFX_TRACK(aGSpin, ATM_VOL(35), ATM_SL_FRQ(30), ATM_NOTE_C3, ATM_DELAY(24));   // SEG Spin
ATM_SFX_TRACK(aGBump, ATM_VOL(50), ATM_SL_VOL((uint8_t)-5), ATM_GLIS(0x80), ATM_NOTE_C5, ATM_DELAY(8));   // SEG Bump
ATM_SFX_TRACK(aGBoing, ATM_VOL(40), ATM_SL_VOL((uint8_t)-1), ATM_VIB(10, 1), ATM_NOTE_C4, ATM_DELAY(20));   // SEG Boing
ATM_SFX_TRACK(aGChime, ATM_VOL(36), ATM_SL_VOL((uint8_t)-1), ATM_NOTE_C6, ATM_DELAY(4), ATM_NOTE_E6, ATM_DELAY(4), ATM_NOTE_G6, ATM_DELAY(4), ATM_NOTE_C7, ATM_DELAY(14));   // SEG Chime

#endif
