// 45 "poke" effects. Each is a list of SFX_SEG(m, Hz, slide Hz/frame, frames) + SFX_END.
// sizeof() of each array is the byte size shown on screen (4 per segment + 1).
// Generated by extras/tools/gen_sfx_demo.py - edit that and re-run, or edit here by hand.
#ifndef POKESFX_H
#define POKESFX_H
#include "sfx.h"

#define H SFX_HZ
#define S SFX_SL
static const uint8_t pJump[] PROGMEM = { SFX_SEG(2, H(300), S(60), 10), SFX_END };   // Jump
static const uint8_t pCoin[] PROGMEM = { SFX_SEG(3, H(1320), S(0), 4), SFX_SEG(2, H(1760), S(0), 14), SFX_END };   // Coin
static const uint8_t pLaser[] PROGMEM = { SFX_SEG(2, H(3000), S(-186), 14), SFX_END };   // Laser
static const uint8_t pHit[] PROGMEM = { SFX_SEG(3, H(1000), S(0), 8), SFX_END };   // Hit
static const uint8_t pExplode[] PROGMEM = { SFX_SEG(1, H(500), S(0), 40), SFX_END };   // Explode
static const uint8_t pPowerUp[] PROGMEM = { SFX_SEG(3, H(523), S(0), 4), SFX_SEG(3, H(659), S(0), 4), SFX_SEG(2, H(784), S(0), 14), SFX_END };   // PowerUp
static const uint8_t pSelect[] PROGMEM = { SFX_SEG(3, H(880), S(0), 4), SFX_END };   // Select
static const uint8_t pFail[] PROGMEM = { SFX_SEG(2, H(440), S(-11), 30), SFX_END };   // Fail
static const uint8_t pBlip[] PROGMEM = { SFX_SEG(3, H(1568), S(0), 3), SFX_END };   // Blip
static const uint8_t pWhoosh[] PROGMEM = { SFX_SEG(2, H(200), S(100), 12), SFX_END };   // Whoosh
static const uint8_t pSiren[] PROGMEM = { SFX_SEG(3, H(600), S(25), 12), SFX_SEG(3, H(900), S(-25), 12), SFX_END };   // Siren
static const uint8_t pGem[] PROGMEM = { SFX_SEG(3, H(2093), S(0), 3), SFX_SEG(3, H(2637), S(0), 3), SFX_SEG(3, H(3136), S(0), 3), SFX_SEG(2, H(4186), S(0), 14), SFX_END };   // Gem
static const uint8_t pBounce[] PROGMEM = { SFX_SEG(3, H(180), S(0), 6), SFX_SEG(2, H(180), S(0), 6), SFX_SEG(1, H(180), S(0), 6), SFX_END };   // Bounce
static const uint8_t pWarp[] PROGMEM = { SFX_SEG(2, H(100), S(30), 28), SFX_END };   // Warp
static const uint8_t pPowerDn[] PROGMEM = { SFX_SEG(3, H(784), S(0), 4), SFX_SEG(3, H(659), S(0), 4), SFX_SEG(3, H(523), S(0), 4), SFX_SEG(2, H(392), S(0), 14), SFX_END };   // PowerDown
static const uint8_t pAlarm[] PROGMEM = { SFX_SEG(3, H(880), S(0), 6), SFX_SEG(3, H(660), S(0), 6), SFX_SEG(3, H(880), S(0), 6), SFX_SEG(3, H(660), S(0), 6), SFX_END };   // Alarm
static const uint8_t pClick[] PROGMEM = { SFX_SEG(3, H(2000), S(0), 3), SFX_END };   // Click
static const uint8_t pThud[] PROGMEM = { SFX_SEG(3, H(120), S(-4), 8), SFX_END };   // Thud
static const uint8_t pZip[] PROGMEM = { SFX_SEG(2, H(4000), S(-200), 12), SFX_END };   // Zip
static const uint8_t pMagic[] PROGMEM = { SFX_SEG(3, H(1568), S(10), 4), SFX_SEG(3, H(2093), S(10), 4), SFX_SEG(3, H(2637), S(10), 4), SFX_SEG(2, H(3136), S(10), 14), SFX_END };   // Magic
static const uint8_t pNPick[] PROGMEM = { SFX_SEG(3, H(659), S(0), 2), SFX_SEG(3, H(784), S(0), 2), SFX_SEG(3, H(1319), S(0), 2), SFX_SEG(2, H(1568), S(0), 10), SFX_END };   // NES Pick
static const uint8_t pNShot[] PROGMEM = { SFX_SEG(3, H(1800), S(-150), 8), SFX_END };   // NES Shot
static const uint8_t pNStomp[] PROGMEM = { SFX_SEG(3, H(300), S(-20), 6), SFX_SEG(2, H(150), S(-5), 10), SFX_END };   // NES Stomp
static const uint8_t pN1up[] PROGMEM = { SFX_SEG(3, H(659), S(0), 4), SFX_SEG(3, H(784), S(0), 4), SFX_SEG(3, H(1319), S(0), 4), SFX_SEG(3, H(1047), S(0), 4), SFX_SEG(3, H(1175), S(0), 4), SFX_SEG(2, H(1568), S(0), 14), SFX_END };   // NES 1UP
static const uint8_t pNPipe[] PROGMEM = { SFX_SEG(2, H(800), S(-18), 30), SFX_END };   // NES Pipe
static const uint8_t pNFire[] PROGMEM = { SFX_SEG(2, H(500), S(0), 18), SFX_END };   // NES Fire
static const uint8_t pNBlock[] PROGMEM = { SFX_SEG(3, H(220), S(0), 3), SFX_SEG(3, H(165), S(0), 3), SFX_END };   // NES Block
static const uint8_t pNDash[] PROGMEM = { SFX_SEG(3, H(500), S(0), 5), SFX_SEG(2, H(500), S(0), 8), SFX_END };   // NES Dash
static const uint8_t pNDead[] PROGMEM = { SFX_SEG(3, H(988), S(0), 4), SFX_SEG(2, H(660), S(-12), 24), SFX_END };   // NES Dead
static const uint8_t pNBeep[] PROGMEM = { SFX_SEG(3, H(1000), S(0), 3), SFX_SEG(3, H(1000), S(0), 3), SFX_END };   // NES Beep
static const uint8_t pTPew[] PROGMEM = { SFX_SEG(3, H(2400), S(-120), 10), SFX_END };   // ATA Pew
static const uint8_t pTCrash[] PROGMEM = { SFX_SEG(1, H(500), S(0), 48), SFX_END };   // ATA Crash
static const uint8_t pTBuzz[] PROGMEM = { SFX_SEG(2, H(110), S(0), 24), SFX_END };   // ATA Buzz
static const uint8_t pTBomb[] PROGMEM = { SFX_SEG(2, H(200), S(-5), 30), SFX_END };   // ATA Bomb
static const uint8_t pTBlip[] PROGMEM = { SFX_SEG(3, H(440), S(0), 4), SFX_END };   // ATA Blip
static const uint8_t pTZap[] PROGMEM = { SFX_SEG(3, H(900), S(100), 8), SFX_END };   // ATA Zap
static const uint8_t pTLose[] PROGMEM = { SFX_SEG(3, H(262), S(0), 6), SFX_SEG(3, H(220), S(0), 6), SFX_SEG(3, H(185), S(0), 6), SFX_SEG(2, H(147), S(0), 16), SFX_END };   // ATA Lose
static const uint8_t pTRumb[] PROGMEM = { SFX_SEG(2, H(55), S(0), 30), SFX_END };   // ATA Rumb
static const uint8_t pTTick[] PROGMEM = { SFX_SEG(3, H(1500), S(0), 2), SFX_END };   // ATA Tick
static const uint8_t pTWin[] PROGMEM = { SFX_SEG(3, H(262), S(0), 5), SFX_SEG(3, H(330), S(0), 5), SFX_SEG(3, H(392), S(0), 5), SFX_SEG(2, H(523), S(0), 14), SFX_END };   // ATA Win
static const uint8_t pGRing[] PROGMEM = { SFX_SEG(3, H(1760), S(0), 4), SFX_SEG(2, H(2637), S(0), 18), SFX_END };   // SEG Ring
static const uint8_t pGSpin[] PROGMEM = { SFX_SEG(2, H(200), S(40), 20), SFX_END };   // SEG Spin
static const uint8_t pGBump[] PROGMEM = { SFX_SEG(3, H(500), S(-30), 5), SFX_SEG(3, H(330), S(0), 4), SFX_END };   // SEG Bump
static const uint8_t pGBoing[] PROGMEM = { SFX_SEG(2, H(300), S(60), 12), SFX_SEG(2, H(700), S(-40), 12), SFX_END };   // SEG Boing
static const uint8_t pGChime[] PROGMEM = { SFX_SEG(3, H(1047), S(0), 4), SFX_SEG(3, H(1319), S(0), 4), SFX_SEG(3, H(1568), S(0), 4), SFX_SEG(2, H(2093), S(0), 20), SFX_END };   // SEG Chime

#undef H
#undef S
#endif
