name=ATMlib
version=1.2.7
author=TEAM a.r.g., Joeri Gantois aka JO3RI, Davey Taylor aka STG
maintainer=joerigantois@gmail.com
sentence=The Arduboy Tracker Music library.
paragraph=A library for playing 4 channel chiptune music and oscilator sounds, intended for use with the Arduboy game system
category=Signal Input/Output
url=https://github.com/T-arg/ATMlib
architectures=avr
includes=ATMlib.h, ATMcmds.h
