#!/usr/bin/env python3
"""
readme_to_html.py - regenerate docs/index.html from README.md, so the web page and the README never drift apart.

Usage (from extras/tools):   python3 readme_to_html.py [../../README.md] [../../docs/index.html]
Needs:  pip install markdown

The README is split into tabs by heading:
  Home          intro, Quick start, Library overview
  API           API, Sound effects, Cues
  Config        Compile-time config
  Format        sections 2 and 3 (song data format, command reference)
  Playroutine   sections 4, 5 and 6 (behaviour, tempo, hop-free loops)
  Songwriting   sections 0, 1, 7 to 12
  Songs         section 13 (catalog)
  Tracker       Tracker editor
Only the <nav> list and the <main> element of docs/index.html are replaced; the head, style, header,
footer and script of the existing page are kept.  The part of the README between <!-- toc:start -->
and <!-- toc:end --> is dropped (the tabs are the table of contents).
"""
import re, sys, os, html
import markdown

readme = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '../../README.md')
page = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), '../../docs/index.html')

TABS = [('home', 'Home'), ('api', 'API'), ('config', 'Config'), ('format', 'Format'),
        ('playroutine', 'Playroutine'), ('guide', 'Songwriting'), ('catalog', 'Songs'), ('tracker', 'Tracker')]
H1 = {'home': 'ATMlib', 'api': 'API', 'config': 'Config', 'format': 'Song format and commands',
      'playroutine': 'How the playroutine behaves', 'guide': 'Songwriting guide', 'catalog': 'Song catalog',
      'tracker': 'ATM Tracker Editor'}


def tab_of(h2, intro_of_part2):
    t = h2.strip()
    if t in ('Quick start', 'Library overview'): return 'home'
    if t in ('API', 'Sound effects', 'Cues'): return 'api'
    if t == 'Compile-time config': return 'config'
    if t == 'Tracker editor': return 'tracker'
    m = re.match(r'(\d+)\.', t)
    if m:
        n = int(m.group(1))
        if n in (2, 3): return 'format'
        if n in (4, 5, 6): return 'playroutine'
        if n == 13: return 'catalog'
        return 'guide'
    if t.startswith('Credits'): return 'credits'
    return None


text = open(readme, encoding='utf-8').read()
text = re.sub(r'<!-- toc:start -->.*?<!-- toc:end -->', '', text, flags=re.S)
lines = text.split('\n')
buckets = {k: [] for k, _ in TABS}
credits = []
cur = 'home'
in_code = False
for l in lines:
    if l.startswith('```'): in_code = not in_code
    if not in_code and l.startswith('# ') and not l.startswith('# ATMlib'):
        cur = 'guide'                      # the part-2 title and its intro
        continue                           # the tab already has an h1
    if not in_code and l.startswith('# ATMlib'):
        continue
    if not in_code and l.startswith('## '):
        t = tab_of(l[3:], False)
        if t == 'credits': cur = 'credits'
        elif t: cur = t
    if not in_code and l.strip() == '---':
        continue
    (credits if cur == 'credits' else buckets[cur]).append(l)

md = markdown.Markdown(extensions=['tables', 'fenced_code'])
GH = 'https://github.com/T-arg/ATMlib/blob/HEAD/'


def render(ls):
    md.reset()
    h = md.convert('\n'.join(ls))
    h = re.sub(r'href="\.?/?((?:extras|examples|src|docs)/[^"#]*)"', lambda m: 'href="' + GH + m.group(1) + '"', h)
    h = h.replace('<blockquote>', '<div class="note">').replace('</blockquote>', '</div>')
    h = h.replace('The full template, <code>docs/ATMconfig.h</code>:',
                  'The full template, <code>docs/ATMconfig.h</code> (you can also <a href="https://t-arg.github.io/ATMlib/ATMconfig.h" download="ATMconfig.h">download ATMconfig.h</a>):')
    h = re.sub(r'<table>', '<div class="table-wrap"><table>', h)
    h = h.replace('</table>', '</table></div>')
    return h


sections = []
for i, (key, label) in enumerate(TABS):
    body = render(buckets[key])
    if key == 'home':
        # first paragraphs sit under "# ATMlib": keep them, add the feature cards as the page already had
        body = '<h1>ATMlib</h1>\n' + body
    else:
        body = f'<h1>{H1[key]}</h1>\n' + body
    if key == 'home':
        body += '\n' + render(credits)
    sections.append(f'        <section id="{key}" class="content-section{" active" if i == 0 else ""}">\n{body}\n        </section>')
nav = '\n'.join(f'            <li><a href="#" class="nav-link{" active" if i == 0 else ""}" data-page="{k}">{lab}</a></li>'
                for i, (k, lab) in enumerate(TABS))

old = open(page, encoding='utf-8').read()
new = re.sub(r'(<nav>\s*<ul>).*?(</ul>\s*</nav>)', lambda m: m.group(1) + '\n' + nav + '\n        ' + m.group(2), old, flags=re.S)
new = re.sub(r'(<main>).*?(</main>)', lambda m: m.group(1) + '\n' + '\n\n'.join(sections) + '\n    ' + m.group(2), new, flags=re.S)
extra_css = '''
        /* generated by readme_to_html.py */
        .table-wrap { overflow-x: auto; }
        .content-section blockquote, .content-section .note { background: #f5f5f3; border-left: 4px solid #4a3b3a; padding: 12px 16px; margin: 16px 0; }
        .content-section .note p { margin-bottom: 0; }
        .content-section h4 { color: #4a3b3a; margin: 18px 0 8px; }
        .content-section hr { border: none; border-top: 2px solid #4a3b3a; margin: 24px 0; }
        .content-section input[type=checkbox] { margin-right: 6px; }
'''
if 'generated by readme_to_html.py' not in new:
    new = new.replace('</style>', extra_css + '    </style>', 1)
open(page, 'w', encoding='utf-8').write(new)
print('wrote', page, len(new), 'bytes;', ', '.join(f'{k}={len(v)} lines' for k, v in buckets.items()))
